# Note that environment variables may be sourced from the shell environment in
# which docker-compose was invoked, or from the defaults specified in '.env'.
version: "3.3"
services:
  server:
    # Simply update this to remove the address to fetch it from DockerHub instead
    # of the local registry.
    image: "localhost:5000/karagog/mysql-db-provider:latest"
    ports:
      - "$APP_PROVIDER_PORT:$APP_PROVIDER_PORT"
      - "$APP_MYSQL_PUBLISHED_PORT:3306"

    environment:
      # Forward some environment variables to keep them consistent with the ports
      # we're forwarding.
      - "APP_PROVIDER_PORT=$APP_PROVIDER_PORT"
      - "APP_MYSQL_PUBLISHED_PORT=$APP_MYSQL_PUBLISHED_PORT"

    # Using tmpfs speeds up the server startup and operation significantly. This
    # is a test database instance server, so the data is not meant to persist.
    tmpfs: "/var/lib/mysql"
