version: "3.9"
services:
  # We need to run a dedicated Mysql server instance to provide the databases.
  mysqld:
    image: "mysql/mysql-server:8.0"

    # Keep the service running even after machine reboots.
    restart: "always"

    ports:
      - "$PROVIDER_MYSQL_PORT:3306"

    # Using tmpfs speeds up the server startup and operation significantly. This
    # is a test database instance server, so the data is not meant to persist.
    tmpfs: "/var/lib/mysql"

    env_file:
      - ".env"

  # Run the provider service alongside Mysql.
  provider:
    # Simply update the DOCKER_REGISTRY_ADDRESS in the .env file (or in your local
    # bash environment) to fetch it from a different registry.
    # See README.md for details.
    image: "${DOCKER_REGISTRY_ADDRESS:-index.docker.io}/karagog/mysql-db-provider:latest"

    healthcheck:
      test: ["CMD", "./healthcheck/healthcheck_/healthcheck"]
      interval: 1m30s
      timeout: 5s
      retries: 3
      start_period: 40s
      
    # Keep the service running even after machine reboots.
    restart: "always"
    ports:
      - "$PROVIDER_PORT:$PROVIDER_PORT"

    env_file:
      - ".env"
