name: Regression Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  regression-test:
    runs-on: ubuntu-latest

    # Run the tests inside the container so they have direct access to the service containers.
    container:
      image:  golang:1.17

    services:
      # The database provider is needed to spawn database instances for
      # unit integration tests.
      database:
        image: mysql:8.0
        volumes:
          - "tmpfs:/var/lib/mysql"
        env:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_ROOT_HOST: "%"

      provider:
        image: karagog/mysql-db-provider:latest
        env:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_ROOT_HOST: "%"

          # We can reference the service's hostname because it's running in a Docker container.
          PROVIDER_MYSQL_ADDRESS: database
          PROVIDER_MYSQL_PORT: 3306
          PROVIDER_PORT: 58615
          PROVIDER_MYSQL_USER: test
          PROVIDER_MYSQL_USER_PASSWORD: test
          PROVIDER_DB_INSTANCES: 20

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: go build -v ./...

    # Keep this around (but commented) because it can be useful to debug why a service is unavailable.
    # - name: Show logs
    #   run: |
    #     echo "${{ toJson(job) }}"
    #     docker logs "${{ job.services.provider.id }}"
    #     docker logs "${{ job.services.database.id }}"

    - name: Test
      # Run all unit tests plus integration tests. We can safely run integration tests because
      # we set up the necessary service containers.
      run: go test -v ./... -tags=integration
      env: 
          # This tells unit tests where to find the instance provider. The hostname lookup works
          # only because the tests are running in a Docker environment with the
          # service containers present.
          DB_INSTANCE_PROVIDER_ADDRESS: provider:58615
