name: Postsubmits
on:
  push:
    branches: [ master ]

jobs:
  smoke:
    # TODO: Evaluate this workflow at ref head after this issue is resolved:
    # https://github.community/t/ref-head-in-reusable-workflows/203690/17
    #
    # Currently when you change this file in a pull request it will call the
    # presubmits from the main branch, which is not what you'd want if you're
    # developing on the workflows themselves.
    uses: karagog/db-provider/.github/workflows/presubmit.yml@master

  # Pre-integration steps include building and deploying a candidate release
  # container for the integration step to follow.
  pre-integrate:
    runs-on: ubuntu-latest
    needs: smoke
    steps:
    - uses: actions/checkout@v2

    - name: Setup Docker Build
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Deploy
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./containers/mysql/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mysql-db-provider:postsubmit

  integrate-and-deploy:
    runs-on: ubuntu-latest
    needs: pre-integrate

    # Run the tests inside the container so they have direct access to the service containers.
    container:
      image:  karagog/cloud-builder:latest

    services:
      # The database provider is needed to spawn database instances for
      # unit integration tests.
      database:
        image: mysql:8.0
        volumes:
          # Using tmpfs dramatically improves the startup time and overall
          # performance of the service. 
          - "tmpfs:/var/lib/mysql"
        env:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_ROOT_HOST: "%"

      provider:
        # TODO: We need to reference the exact version that was built in the pre-integrate
        # step. Currently this can race if multiple postsubmits are done simultaneously.
        # I think we can do that by using job outputs to pass the version string.
        image: karagog/mysql-db-provider:postsubmit
        env:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_ROOT_HOST: "%"

          # We can reference the service's hostname because it's running in a Docker environment.
          PROVIDER_MYSQL_ADDRESS: database
          PROVIDER_MYSQL_PORT: 3306
          PROVIDER_PORT: 58615
          PROVIDER_MYSQL_USER: test
          PROVIDER_MYSQL_USER_PASSWORD: test
          PROVIDER_DB_INSTANCES: 20

    steps:
      - uses: actions/checkout@v2

      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Integration Tests
        run: go test -v ./... -tags=integration
        env:
          DB_INSTANCE_PROVIDER_ADDRESS: provider:58615

      # Integration tests passed, proceed to deploy:
      - name: Setup Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Deploy Latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./containers/mysql/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mysql-db-provider:latest
