name: Presubmits

on:
  pull_request:
    branches: [ master ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Check Format
      run: gofmt -s -w .

    - name: Run Unit Tests
      run: |
        go build -v ./...
        go test -v ./...
      